### PR TITLE
Add firefox support

### PR DESCRIPTION
**Pull request by dougt**

### CODE REVIEW

**Comment by dougt** [comment]
mostly looking for feedback. do not merge as-is.

**Comment by johnmellor** [comment]
Hi Doug, exciting to see this progressing! I've left comments on the individual commits. I'd be happy to incorporate such changes into the main repository.

**Comment by johnmellor** [comment]
I've landed versions of all the patches to the master branch (except [][1]

**Comment by johnmellor** [comment]
I've landed versions of all these patches (except [Remove test for window.PushManager and navigator.push][1] which I confirmed was no longer necessary in the Firefox build you send me). This repository now officially supports Firefox SimplePush!

[1]: https://github.com/dougt/push-api-appengine-demo/commit/90af886acc21a0d6905b93e89695663d1443d1d0

**Pull request closed without merging**
